### ISSUE TITLE
Convert arrow functions

### ISSUE THREAD

**Issue by bojan88** [riot/babel-preset-es2015-riot#10]
Should this preset convert arrow functions to es5 functions in riot.js tags? I'm trying to do that, but it's not working

**Comment by bojan88** [comment]
To be more clear, here's the browserify part with transformations

```
var b = browserify({
    entries: 'src/index.js',
    debug: true
  }).transform(riotify, {type: 'babel', style: 'scss'})
    .transform(babelify, {presets: ['es2015-riot']});
```

and example arrow functions from tag

```
this.exampleFn = e => {/*code*/}
this.on('update', () => {/*code*/});
```

**Comment by cognitom** [comment]
@bojan88 Yes, it should.
This preset includes `babel-plugin-transform-es2015-arrow-functions`.
https://github.com/riot/babel-preset-es2015-riot/blob/master/index.js#L6

How about this?

```javascript
.transform(babelify, { babelrc: false, presets: ['es2015-riot'] })
```

**Comment by bojan88** [comment]
Nothing changed by adding `babelrc: false`. There wasn't a .babelrc file in the project

**Comment by bojan88** [comment]
I've found solution. Removed the presets argument from gulp build transformation, and added it in package.json.
```"babel": {
  "presets": ["es2015-riot"]
},```
