### ISSUE TITLE
Update to use preset-env

### ISSUE THREAD

**Issue by tyteen4a03** [riot/babel-preset-es2015-riot#20]
Will this package be updated to use [babel-preset-env](https://babeljs.io/docs/plugins/preset-env/)?

**Comment by GianlucaGuarini** [comment]
babel preset env can be mixed to this preset.. no need to ad it here

**Comment by surgeboris** [comment]
@GianlucaGuarini  [I attempted to mix in babel-preset-env into the webpack example](https://github.com/riot/examples/compare/gh-pages...surgeboris:gh-pages) and I get the following error:

`Uncaught TypeError: Cannot set property 'number' of undefined`

Reversing preset's order (`"presets": [ "es2015-riot", "env" ]`) still produces the same error.

I've tried to google the solution, but haven't found anything.

What am I doing wrong?
