### ISSUE TITLE
Update to use preset-env

### ISSUE THREAD

**Issue by surgeboris** [riot/babel-preset-es2015-riot#24]
I'm sorry for opening a duplicate of issue #20, but I'm too interested to get a response [to my comment there](https://github.com/riot/babel-preset-es2015-riot/issues/20#issuecomment-370179498):

@GianlucaGuarini  [I attempted to mix in babel-preset-env into the webpack example](https://github.com/riot/examples/compare/gh-pages...surgeboris:gh-pages) and I get the following error:

`Uncaught TypeError: Cannot set property 'number' of undefined`

Reversing preset's order (`"presets": [ "es2015-riot", "env" ]`) still produces the same error.

I've tried to google the solution, but haven't found anything.

What am I doing wrong?

**Comment by GianlucaGuarini** [comment]
could you please dump also the error stack trace? Thanks

**Comment by GianlucaGuarini** [comment]
you can just remove [this line](https://github.com/riot/examples/blob/gh-pages/webpack/webpack.config.js#L20) and everything will be fine. The old babel env overrides [this option](https://github.com/riot/babel-preset-es2015-riot/blob/master/index.js#L22). I am looking forward to updating the webpack example once babel@7 will be officially released. Thanks for this issue

**Comment by surgeboris** [comment]
FYI: by removing the line you've suggested I'm effectively disabling transpilation altogether. I haven't noticed it until I tried to check my code in IE11...

**Comment by GianlucaGuarini** [comment]
@surgeboris have you tried submitting this issue to babel? This is not really an issue with this riot preset but with the babel configuration rules

**Comment by surgeboris** [comment]
@GianlucaGuarini I've considered submitting issue to babel, but I'm not sure what should I ask for in this issue... To me it looks more like the problem with presets, not with babel itself...

My guess is that there are two ways to solve this issue:
1. Either rewrite "babel-preset-es2015-riot" on top of "babel-env"
2. Or persuade babel developers to introduce "allowTopLevelThis" configurable option for "babel-env" preset

Do you want me to open issue for the second way?

**Comment by GianlucaGuarini** [comment]
@surgeboris I would recommend you first of all to do not use software that is still in [beta release](https://github.com/babel/babel/blob/master/packages/babel-preset-env/package.json#L3) for production apps. Second you might ask to the babel community how to handle this option with the new babel env setup. I will update this repo once babel@7 will be officially released
