### ISSUE TITLE
How to override plugin options?

### ISSUE THREAD

**Issue by rightwork** [riot/babel-preset-es2015-riot#25]
I'd like to turn on async and asyncGenerators (from false to true) in index.js:

`[require('babel-plugin-transform-regenerator'), { 'async': true, 'asyncGenerators': true }]`

Is there a way to configure that for my riot tags through webpack config or otherwise, or should I just create a fork of this repo?  I'm already using babel-preset-env for my .js files, so they're already good.

Thanks.

**Comment by rap2hpoutre** [comment]
@rightwork Did you found an answer to your question?

**Comment by rightwork** [comment]
Yes. I just cloned the repo and made the above change manually.

This can be closed, if that's what your asking.

**Comment by rap2hpoutre** [comment]
I'm not the repo owner, I was just asking. Still I used this solution to avoid re-creating something:

```
# compile your tags using pure es6 code
riot tags/folder dist/es6.tags.js
# convert your es6 to valid es5 code
babel es6.tags.js --out-file tags.js
```
Source: https://riot.js.org/guide/compiler/

**Comment by rightwork** [comment]
Thanks.  I'm using webpack with the tag-loader plugin.  I'm sure I could use your snippet and then just feed the files into my webpack babel loader plugin.  But, what I have works for now.  I've upset the webpack and babel gods enough to know when to leave well enough alone ;)

**Comment by rightwork** [comment]
I'm closing this, since the few solutions listed here are sufficient.
